### ISSUE TITLE
Issue with library generation with owl bot

### ISSUE THREAD

**Issue by sofisl** [googleapis/python-logging#389]
Issue with library generation:

https://pantheon.corp.google.com/cloud-build/builds;region=global/555fc14d-6323-48f9-840e-65354b18b8f8;step=0?project=repo-automation-bots

```
Traceback (most recent call last):
  File "/workspace/python-logging/owlbot.py", line 101, in <module>
    s.shell.run(["nox", "-s", "blacken"], hide_output=False)
  File "/synthtool/synthtool/shell.py", line 39, in run
    raise exc
  File "/synthtool/synthtool/shell.py", line 27, in run
    return subprocess.run(
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nox', '-s', 'blacken']' returned non-zero exit status 1.
```

**Comment by parthea** [comment]
This was resolved. I forgot to close the bug.
