### ISSUE TITLE
protobuf TypeError with protobuf v4

### ISSUE THREAD

**Issue by psongers** [googleapis/python-logging#559]
The latest version of protobuf 4.21.0 is incompatible with the latest release of this library

#### Environment details

  - OS type and version: 
    - Mac/linux
  - Python version: `python --version`
    - Python 3.10.2
  - pip version: `pip --version` 
    - pip 22.0.2
  - `google-cloud-logging` version: `pip show google-cloud-logging` 
    - Name: google-cloud-logging
Version: 3.1.1

#### Steps to reproduce

  1. pip install google-cloud-logging
  2. pip install protobuf==4.21.0
  3. run python and run `import google.cloud.logging`

#### Code example

```python
import google.cloud.logging
```

#### Stack trace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/patrick/dev/test/venv/lib/python3.10/site-packages/google/cloud/logging/__init__.py", line 18, in <module>
    from google.cloud.logging_v2 import __version__
  File "/Users/patrick/dev/test/venv/lib/python3.10/site-packages/google/cloud/logging_v2/__init__.py", line 25, in <module>
    from google.cloud.logging_v2.client import Client
  File "/Users/patrick/dev/test/venv/lib/python3.10/site-packages/google/cloud/logging_v2/client.py", line 25, in <module>
    from google.cloud.logging_v2._helpers import _add_defaults_to_filter
  File "/Users/patrick/dev/test/venv/lib/python3.10/site-packages/google/cloud/logging_v2/_helpers.py", line 25, in <module>
    from google.cloud.logging_v2.entries import LogEntry
  File "/Users/patrick/dev/test/venv/lib/python3.10/site-packages/google/cloud/logging_v2/entries.py", line 31, in <module>
    import google.cloud.audit.audit_log_pb2  # noqa: F401
  File "/Users/patrick/dev/test/venv/lib/python3.10/site-packages/google/cloud/audit/audit_log_pb2.py", line 62, in <module>
    _descriptor.FieldDescriptor(
  File "/Users/patrick/dev/test/venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by luisgc93** [comment]
I confirm I have the same issue. Pinning protobuf==3.20.1 fixed the error for me.

**Comment by dshinzie** [comment]
Pinning protobuf==3.20.1 has fixed the issue for me as well.

**Comment by hsuyuming** [comment]
Sounds like protobuf just release new version 9hr ago. https://pypi.org/project/protobuf/#history.
And most of google libraries's dependency setup is "protobuf >= 3.12.0". then it will install protobuf  4.21.0 during that time..... https://github.com/googleapis/python-api-core/blob/main/setup.py#L33
I also pinning the version to  3.20.1  too. 
Will anyone fix this issue in the future?

**Comment by hsuyuming** [comment]
protobuf change their release version back to 3.12.0. https://pypi.org/project/protobuf/#history. so i think people don't need to pinned this version currently.

**Comment by psongers** [comment]
I don't think this is fixed. I have just tried with 4.21.1 and I'm receiving the same error.
