### ISSUE TITLE
Error on batch.commit() after upgrading python to 3.11 and google-cloud-logging to 3.5 (from 3.0).

### ISSUE THREAD

**Issue by ayyoubelamrani4** [googleapis/python-logging#725]
#### Environment details

  - Python version: 3.11.1
  - `google-cloud-logging` version: 3.5.0

#### Steps to reproduce

Started happening on production after doing some upgrades, among other things:
- upgrading python to 3.11.1 from 3.10
- upgrading google-cloud-logging from 3.0.0 to 3.5.0

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/google/cloud/logging_v2/handlers/transports/background_thread.py", line 115, in _safely_commit_batch
    batch.commit()
  File "/usr/local/lib/python3.11/site-packages/google/cloud/logging_v2/logger.py", line 474, in commit
    raise e
  File "/usr/local/lib/python3.11/site-packages/google/cloud/logging_v2/logger.py", line 467, in commit
    client.logging_api.write_entries(
  File "/usr/local/lib/python3.11/site-packages/google/cloud/logging_v2/_gapic.py", line 163, in write_entries
    self._gapic_api.write_log_entries(request=request)
  File "/usr/local/lib/python3.11/site-packages/google/cloud/logging_v2/services/logging_service_v2/client.py", line 726, in write_log_entries
    response = rpc(
```

**Comment by gkevinzheng** [comment]
Could you paste in the code that generates this stack trace?
