### ISSUE TITLE
 504 Deadline Exceeded error with default parameters

### ISSUE THREAD

**Issue by NewGlad** [googleapis/python-logging#737]
At the start of my program running on the Google Cloud, I placed the most basic example from the docs:
```
import logging
import google.cloud.logging
from google.cloud.logging_v2.handlers import CloudLoggingHandler
client = google.cloud.logging.Client()
handler = CloudLoggingHandler(client)
cloud_logger = logging.getLogger('cloudLogger')
cloud_logger.setLevel(logging.INFO)
cloud_logger.addHandler(handler)
cloud_logger.error('bad news')  # API call
```

But I am getting the following traceback in my logs

```

Traceback (most recent call last):
  File "/deploy/venv/lib/python3.11/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
           ^^^^^^^^
  File "/deploy/venv/lib/python3.11/site-packages/google/api_core/timeout.py", line 99, in func_with_timeout
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/deploy/venv/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 52, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/deploy/venv/lib/python3.11/site-packages/google/cloud/logging_v2/handlers/transports/background_thread.py", line 115, in _safely_commit_batch
    batch.commit()
  File "/deploy/venv/lib/python3.11/site-packages/google/cloud/logging_v2/logger.py", line 467, in commit
    client.logging_api.write_entries(
  File "/deploy/venv/lib/python3.11/site-packages/google/cloud/logging_v2/_gapic.py", line 163, in write_entries
    self._gapic_api.write_log_entries(request=request)
  File "/deploy/venv/lib/python3.11/site-packages/google/cloud/logging_v2/services/logging_service_v2/client.py", line 726, in write_log_entries
    response = rpc(
               ^^^^
  File "/deploy/venv/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deploy/venv/lib/python3.11/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/deploy/venv/lib/python3.11/site-packages/google/api_core/retry.py", line 205, in retry_target
    raise exceptions.RetryError(
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling target function, last exception: 504 Deadline Exceeded
```
Looks like I need to tweak some parameters, could you please provide any recommendations?
Perhaps for code running on Google Cloud, `google.cloud.logging_v2.handlers.structured_log.StructuredLogHandler` is sufficient since the stdout stream is parsed by the Cloud infrastructure?

**Comment by chrisK824** [comment]
Hey there @NewGlad , I face the same issue these days. Any chance you found more on this?  How was that issue closed in the first place? Thanks a lot in advance.

**Comment by ohado-di** [comment]
same here. facing the same issue :(

**Comment by tlienart** [comment]
I don't have a solution but also ran against this exact issue. Maybe useful to note that this is in the GCP issue tracker too: https://issuetracker.google.com/issues/319693075#comment8 (without solution either).
