### ISSUE TITLE
google.api_core.exceptions.Unknown: None Stream removed when using library in CloudFunction

### ISSUE THREAD

**Issue by MaxTeiger** [googleapis/python-logging#832]
Hello ! 

I have a problem which looks a lot like [this one](https://github.com/googleapis/google-cloud-python/issues/6645) when using `google-cloud-logging==3.8.0` and `log_struct` in cloud functions. Everything is working fine until my CloudFunction scales (it is supposed to).
I get a lot of errors like the one specified above (I outlined where it is happening in my stack trace)

Moreover, it seems that my code blocks on these lines (`logger.log_struct()`), making my whole cloudfunction timeout. 

Is there a way to make these call scalable ? Or at least to run them in the background so even if it timeout, my cloudfunction doesn't fail ?

Thank you very much !

#### Environment details

  - OS type and version: Cloud Function v2 
  - Python version: Python3.10
  - pip version: `pip --version`
  - `google-cloud-logging` version: `google-cloud-logging==3.8.0`

#### Steps to reproduce

  1. Use logger.client.log_struct(log_entry) in your cloud function code
  2. Scale the cloud function to 10+ instances
  3. Observe the logs (and the function failling)

#### Code example

Here is my simplified code :
```python
from google.cloud import logging

logger = logging.Client().logger('your_logger_name')

def main(cloud_event): 
    ...
    log_entry = {
        'message'     : f'Whatever you want',
        'other_computed_attribute': f'{other_computed_attribute}'
    }
    logger.log_struct(log_entry, severity='INFO')

```

#### Stack trace
```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 79, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/grpc/_channel.py", line 1160, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
 status = StatusCode.UNKNOWN
 details = "Stream removed"
 debug_error_string = "UNKNOWN:Error received from peer {grpc_message:"Stream removed", grpc_status:2, created_time:"2023-12-15T14:39:12.20370222+00:00"}"
 >
 The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/functions_framework/__init__.py", line 178, in view_func
    function(event)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/functions_framework/__init__.py", line 74, in wrapper
    return func(*args, **kwargs)

<------ HERE IS WHERE THE ERROR HAPPENS IN MY CODE -->
  File "/workspace/main.py", line 189, in main
    logger.log_struct(log_entry, severity='INFO')
<---------------------------------------------------->

  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/cloud/logging_v2/logger.py", line 219, in log_struct
    self._do_log(client, StructEntry, info, **kw)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/cloud/logging_v2/logger.py", line 168, in _do_log
    client.logging_api.write_entries(entries, partial_success=True)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/cloud/logging_v2/_gapic.py", line 163, in write_entries
    self._gapic_api.write_log_entries(request=request)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/cloud/logging_v2/services/logging_service_v2/client.py", line 727, in write_log_entries
    response = rpc(
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 81, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.Unknown: None Stream removed
```

**Comment by gkevinzheng** [comment]
@MaxTeiger If you're having issues with gRPC you can try using the `StructuredLogHandler` class for logging. It logs to stdout, then another agent should propagate these logs to Cloud Logging.

**Comment by MaxTeiger** [comment]
> @MaxTeiger If you're having issues with gRPC you can try using the `StructuredLogHandler` class for logging. It logs to stdout, then another agent should propagate these logs to Cloud Logging.

I'll have a look at this, thank you :)
